import os.path

Import("env","libRHVoice_core")
local_env=env.Clone()
local_env["libversion"]="1.0.0"
local_env["liblevel"]=2
local_env.Prepend(LIBS=libRHVoice_core)
src=["native.cpp"]
native=local_env.BuildLibrary("jni",src)
if env["PLATFORM"]!="win32":
    local_env.InstallLibrary(native)
